version: "3"

services:
    db:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ../database/mongo:/data/db
    server:
        build: ./server
        ports:
            - 3001:3001
        environment:
            GITHUB_CLIENT_ID:
            GITHUB_CLIENT_SECRET:
        depends_on:
            - db
    website:
        build: ./page
        ports:
            - 80:80
        depends_on:
            - server
